version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = false
s3_prefix = "sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
