AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Function using API Gateway that interacts with DynamoDB Visitor Counter

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11
    MemorySize: 128

Resources:

  VisitorCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: visitor_counter_v1
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: interact_with_dynamo_v1
      Handler: dynamo_api.lambda_handler
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME: visitor_counter_v1
      Events:
        VisitorApi:
          Type: Api
          Properties:
            Path: /counter
            Method: ANY
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: !GetAtt VisitorCounterTable.Arn

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/counter"
